### ISSUE TITLE
Bug in optimization in commit b0dd2ea

### ISSUE THREAD

**Issue by vassvik** [robstolarz/rsht#20]
Seems to not work on collision?

Reverting this commit fixes the bug: 
https://github.com/robstolarz/rsht/commit/b0dd2ea242ce68bf5e206a0e0e9afd6a1e7cb64f

**Comment by robstolarz** [comment]
Oops, forgot to mark this as closed by https://github.com/robstolarz/rsht/commit/693e4b2cc094d72616d82f05cf5604558338b5cb, thanks
